require "../Package/Package.k"
require "../ComponentType/ComponentType.k"
require "../ComponentImplementation/ComponentImplementation.k"
require "../Subcomponent/Subcomponent.k"
require "../SubprogramCall/SubprogramCall.k"
require "../AnnexSubclauseAnnexLibrary/AnnexSubclauseLibrary.k"
require "../FeatureShareAccess/FeatureShareAccess.k"
require "../AbstractFeature/AbstractFeature.k"
require "../FeatureGroupType/FeatureGroupType.k"
require "../Port/Port.k"
require "../SubprogramGroupAccess/SubprogramGroupAccess.k"
require "../SubprogramParameter/SubprogramParameter.k"
require "../DataComponentAccess/DataComponentAccess.k"
require "../BusComponentAccess/BusComponentAccess.k"
require  "../Connection/Connection.k"
require "../FeatureConnection/FeatureConnection.k"
require "../PortConnection/PortConnection.k"
require "../ParameterConnection/ParameterConnection.k"
require "../AccessConnection/AccessConnection.k"
require "../FeatureGroupConnection/FeatureGroupConnection.k"
require "../FlowSpecification/FlowSpecification.k"
require "../FlowImplementation/FlowImplementation.k"
require "../EndToEndFlow/EndToEndFlow.k"
require "../PropertySet/PropertySet.k"
require "../PropertyType/PropertyType.k"
require "../PropertyDefination/PropertyDefination.k"
require "../PropertyConstant/PropertyConstant.k"
require "../PropertyAssociation/PropertyAssociation.k"
require "../PropertyExpression/PropertyExpression.k"
require "../ModesAndModeTransition/ModesAndModeTransition.k"
require "../LexicalElement/LexicalElement.k"

module AADL-SYNTAX


endmodule

module AADL

	imports AADL-SYNTAX

endmodule